# Generated by Django 6.1 on 2026-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_curriculum_and_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='extraction_quality',
            field=models.CharField(default='success', help_text='Extraction status', max_length=50),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_scanned',
            field=models.BooleanField(default=False, help_text='True if scanned/image-only PDF requiring OCR'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='page_count',
            field=models.IntegerField(default=1, help_text='Total number of document pages'),
        ),
    ]
