# Generated by Django 6.1 on 2026-08-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('achievement_type', models.CharField(choices=[('test_excellence', 'Mock Test Excellence'), ('study_plan', 'Study Plan Completion'), ('placement_readiness', 'Placement Readiness Achievement')], default='test_excellence', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
