"""Core Views — Landing, About, Contact, FAQ pages"""
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings


def landing(request):
    """Main landing page with all sections. Stats from DB with fallback."""
    from accounts.models import User, StudentProfile

    try:
        total_students = User.objects.filter(role='student').count()
    except Exception:
        total_students = 0

    try:
        from companies.models import Company
        total_companies = Company.objects.count()
    except Exception:
        total_companies = 0

    try:
        from quiz.models import Question
        total_questions = Question.objects.count()
    except Exception:
        total_questions = 0

    # Use real counts + clearly labelled demo data
    stats = {
        'total_students': total_students if total_students > 0 else 0,
        'total_companies': total_companies if total_companies > 0 else 0,
        'total_questions': total_questions if total_questions > 0 else 0,
        'placement_rate': 85,  # Fictional demo metric — for display purposes
        'is_demo': total_students == 0,  # Flag: shows demo banner if no real data
    }

    context = {
        'stats': stats,
        'features': [
            {'icon': 'bi-robot', 'title': 'AI Study Planner', 'desc': 'OpenRouter AI generates personalized study plans based on your subjects, deadlines, and available time.', 'color': 'primary', 'link': '/study-planner/'},
            {'icon': 'bi-briefcase-fill', 'title': 'Placement Preparation', 'desc': 'Company-specific questions, aptitude tests, and mock interviews tailored to your target companies.', 'color': 'success', 'link': '/placement/'},
            {'icon': 'bi-file-earmark-person', 'title': 'AI Resume Analyzer', 'desc': 'Get an ATS-style score, keyword suggestions, and AI-powered improvement recommendations.', 'color': 'warning', 'link': '/resume/'},
            {'icon': 'bi-chat-dots-fill', 'title': 'AI Mock Interviews', 'desc': 'Practice with an AI interviewer that evaluates your answers for accuracy, clarity, and completeness.', 'color': 'danger', 'link': '/interview/'},
            {'icon': 'bi-bar-chart-line-fill', 'title': 'Skill Gap Analysis', 'desc': 'Identify exactly which skills are missing for your target role with actionable learning paths.', 'color': 'info', 'link': '/placement/skill-gap/'},
            {'icon': 'bi-trophy-fill', 'title': 'Progress Analytics', 'desc': 'Detailed charts, placement readiness score, streaks, and performance insights.', 'color': 'secondary', 'link': '/analytics/'},
        ],
        'ai_features': [
            {'emoji': '&#129302;', 'title': 'AI Study Planner', 'desc': 'Personalized weekly plans generated by NVIDIA Nemotron AI based on your subjects and available time.'},
            {'emoji': '&#128200;', 'title': 'Skill Gap Analyzer', 'desc': 'Deep analysis of your current skills vs what top companies require for your target role.'},
            {'emoji': '&#127919;', 'title': 'Placement Readiness Score', 'desc': 'A transparent, data-driven score that shows exactly how interview-ready you are.'},
            {'emoji': '&#128221;', 'title': 'ATS Resume Analyzer', 'desc': 'Upload your resume and get ATS score, missing keywords, and section-by-section suggestions.'},
            {'emoji': '&#128188;', 'title': 'AI Mock Interviewer', 'desc': 'Practice real interviews with an AI that evaluates technical accuracy, completeness, and clarity.'},
            {'emoji': '&#127916;', 'title': 'AI Doubt Solver', 'desc': 'Get instant answers to CS doubts — DSA, DBMS, OS, CN, programming questions.'},
        ],
        'testimonials': [
            {'name': 'Priya Sharma', 'role': 'SDE at Google', 'company': 'Google', 'text': 'The AI study planner kept me focused and consistent. I went from 30% to 78% placement readiness in 8 weeks!', 'avatar': 'PS', 'rating': 5},
            {'name': 'Rahul Gupta', 'role': 'Software Engineer at Microsoft', 'company': 'Microsoft', 'text': 'The AI mock interviews were incredibly realistic. The skill gap analysis showed me exactly what to study.', 'avatar': 'RG', 'rating': 5},
            {'name': 'Anjali Verma', 'role': 'Data Analyst at Amazon', 'company': 'Amazon', 'text': 'My resume ATS score jumped from 45% to 91% after following the AI suggestions. Got 3 interview calls!', 'avatar': 'AV', 'rating': 5},
            {'name': 'Karthik Rajan', 'role': 'Backend Engineer at Flipkart', 'company': 'Flipkart', 'text': 'The placement readiness score was spot-on. When it reached 80%, I started getting shortlisted consistently.', 'avatar': 'KR', 'rating': 5},
        ],
        'faqs': [
            {'q': 'Is this platform free for students?', 'a': 'Yes! PlacementPro is completely free for B.Tech students. All AI features, mock tests, and study tools are included.'},
            {'q': 'How does the AI Study Planner work?', 'a': 'Our AI analyzes your subjects, exam dates, available study hours, and weak areas to generate a personalized weekly schedule that adapts as you progress.'},
            {'q': 'What is the Placement Readiness Score?', 'a': 'It is a transparent score (0-100%) calculated from your DSA performance (30%), technical knowledge (20%), aptitude (15%), resume quality (15%), projects (10%), and communication (10%).'},
            {'q': 'How does the AI Mock Interview work?', 'a': 'You choose a role and difficulty. The AI asks technical and HR questions, evaluates your answer for accuracy and completeness, gives feedback, and asks a follow-up question.'},
            {'q': 'Can I download my resume as PDF?', 'a': 'Yes. You can build your resume section by section, get AI feedback, and download it as a professional PDF.'},
            {'q': 'Which companies are covered?', 'a': 'Our demo data covers 150+ companies including FAANG, TCS, Infosys, Wipro, Accenture, Cognizant, HCL, and many product companies.'},
        ],
        'how_it_works': [
            {'step': 1, 'title': 'Create Your Profile', 'desc': 'Enter your branch, skills, CGPA, target companies, and available study time.', 'icon': 'bi-person-fill-add'},
            {'step': 2, 'title': 'Get Your Analysis', 'desc': 'AI analyzes your profile and shows your placement readiness score and skill gaps.', 'icon': 'bi-graph-up-arrow'},
            {'step': 3, 'title': 'Follow Your Plan', 'desc': 'Follow the personalized AI study plan, take mock tests, and practice interviews.', 'icon': 'bi-journal-check'},
            {'step': 4, 'title': 'Get Placed', 'desc': 'Track your progress as your readiness score rises and land your dream job.', 'icon': 'bi-trophy-fill'},
        ],
        'readiness_items': [
            {'name': 'DSA & Problem Solving', 'score': 78, 'width': '78%', 'color': '#6366f1'},
            {'name': 'Aptitude & Reasoning', 'score': 82, 'width': '82%', 'color': '#10b981'},
            {'name': 'DBMS & OS', 'score': 70, 'width': '70%', 'color': '#f59e0b'},
            {'name': 'Projects & Portfolio', 'score': 60, 'width': '60%', 'color': '#ef4444'},
            {'name': 'Resume Quality', 'score': 91, 'width': '91%', 'color': '#10b981'},
            {'name': 'Communication', 'score': 75, 'width': '75%', 'color': '#8b5cf6'},
        ],
    }

    return render(request, 'core/landing.html', context)


def about(request):
    return render(request, 'core/about.html')


def faq(request):
    return render(request, 'core/faq.html')


def features(request):
    return render(request, 'core/features.html')


def contact(request):
    """Contact form submission."""
    if request.method == 'POST':
        name = request.POST.get('name', '').strip()
        email = request.POST.get('email', '').strip()
        subject = request.POST.get('subject', '').strip()
        message_text = request.POST.get('message', '').strip()

        if name and email and message_text:
            try:
                send_mail(
                    subject=f'[Contact Form] {subject} — {name}',
                    message=f'From: {name} <{email}>\n\n{message_text}',
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[settings.DEFAULT_FROM_EMAIL],
                    fail_silently=True,
                )
                messages.success(request, '✅ Your message has been sent! We will get back to you within 24 hours.')
            except Exception:
                messages.error(request, 'Failed to send. Please try again.')
        else:
            messages.error(request, 'Please fill in all fields.')

        return redirect('core:contact')

    return render(request, 'core/contact.html')


def switch_role(request, role):
    """Instant role switcher for demonstration and frictionless testing."""
    from accounts.models import User
    from django.contrib.auth import login

    role = role.lower()
    user = None
    target_url = '/dashboard/'

    if role == 'admin':
        user = User.objects.filter(email='11231@gmail.com').first() or \
               User.objects.filter(username='11231@gmail.com').first() or \
               User.objects.filter(username='11231').first() or \
               User.objects.filter(role='admin').first()
        target_url = '/dashboard/admin/'
    else:
        user = User.objects.filter(username='student1').first() or \
               User.objects.filter(role='student').first()
        target_url = '/dashboard/'

    if user:
        request.session['active_role'] = role
        login(request, user, backend='accounts.backends.MultiIdentifierBackend')
        messages.success(request, f'⚡ Switched to {role.capitalize()} view ({user.get_full_name() or user.username})')

    return redirect(target_url)


def concept_note(request):
    """Client-facing Concept Note and Comprehensive Project Documentation with Print-to-PDF."""
    return render(request, 'core/concept_note.html')
