# Generated by Django 6.1 on 2026-08-14 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0002_alter_dailystudylog_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_score', models.IntegerField(default=0, help_text='0-100 percentage score')),
                ('quiz_accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('study_minutes', models.IntegerField(default=0)),
                ('is_weak', models.BooleanField(default=False, help_text='True if mastery < 50%')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to='studyplanner.studysubject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='studyplanner.topic')),
            ],
            options={
                'ordering': ['mastery_score', 'topic__name'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
