# Generated by Django 6.1 on 2026-10-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0003_topicmastery'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysubject',
            name='syllabus_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabi/'),
        ),
        migrations.AddField(
            model_name='studysubject',
            name='syllabus_text',
            field=models.TextField(blank=True, help_text='Extracted or pasted syllabus content for AI queries'),
        ),
    ]
