# Generated by Django 6.1 on 2026-08-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('company_type', models.CharField(choices=[('product', 'Product Based'), ('service', 'Service Based'), ('startup', 'Startup'), ('mnc', 'MNC'), ('psu', 'PSU'), ('consulting', 'Consulting')], default='service', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('min_package', models.DecimalField(decimal_places=2, default=0, help_text='In LPA (Lakhs Per Annum)', max_digits=10)),
                ('max_package', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('eligible_branches', models.TextField(blank=True, help_text='Comma-separated branch codes e.g. CSE,ECE,IT')),
                ('backlogs_allowed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
